apiVersion: v1
kind: Service
metadata:
  name: {{ $.Chart.Name }}
spec:
  selector:
    app: {{ $.Chart.Name }}
  ports:
    - name: http
      port: {{ $.Values.service.port }}
      targetPort: {{ $.Values.service.targetServicePort }}
      protocol: TCP
  type: ClusterIP

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ .Chart.Name }}-ingress"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: |
        Host(`quiz.aqua.denisovv.me`)
      services:
        - name: {{ .Chart.Name }}
          port: {{ .Values.service.port }}
  tls:
    certResolver: le